[Content]
Autologin=yes
Ssh=yes
Bootable=no
Bootloader=none
Packages=e2fsprogs
          file

[Config]
Profiles=kernel

[Build]
BuildSources=$GITHUB_WORKSPACE:kernel
Environment=SELFTESTS=1
            SELFTESTS_TARGETS="mount mount_setattr filelock tmpfs pidfd pid_namespace cachestat"

[Output]
Format=disk

[Runtime]
Firmware=linux
RAM=8G
CPUs=4
KernelCommandLineExtra=enforcing=0 rw systemd.mask=var-lib-nfs-rpc_pipefs.mount debug no_console_suspend systemd.firstboot=no
